### ISSUE TITLE
Set Listeners method AwesomeNotifications().setListeners()

### ISSUE THREAD

**Issue by arthurgichuhi** [rafaelsetragni/awesome_notifications#816] opened 2023-07-12 09:17 UTC
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**
The method AwesomeNotifications().setListeners() that enables notifications to be delivered after its called is producing an error saying:
_**The method 'setListeners' isn't defined for the type 'AwesomeNotifications'.**_

## **2 - Provide us as much information as possible**

To help us to understand your issue, provide with your bug report all the relevant informations, such as:

* Your plugins list inside the file `pubspec.yaml` (at least all notification plugins)
 cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.2
  flutter:
    sdk: flutter
  google_fonts: ^4.0.1
  jiffy: ^5.0.0
  firebase_auth: ^4.1.4
  google_sign_in: ^6.0.1
  cloud_firestore: ^4.3.1
  firebase_core: ^2.4.1
  firebase_database: ^10.0.6
  shared_preferences: ^2.0.15
  flutter_riverpod: ^2.1.1
  flutter_contacts: ^1.1.5+1
  image_picker: ^0.8.6
  firebase_storage: ^11.0.6
  uuid: ^3.0.7
  video_player: ^2.6.0
  emoji_picker_flutter: ^1.5.1
  giphy_get: ^3.1.1
  flutter_sound: ^9.2.13
  permission_handler: ^10.2.0
  path_provider: ^2.0.11
  audioplayers: ^4.0.0
  swipe_to: ^1.0.2
  flutter_video_info: ^1.3.1
  story_view: ^0.14.0
  awesome_notifications: any
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  videosdk: ^1.0.13
  firebase_messaging: ^14.2.4
   http: ^0.13.5
  flex_color_picker: ^3.2.0
  video_trimmer:
    git:
      url: https://github.com/arthurgichuhi/video_trimmer
  country_code_picker: ^3.0.0
  url_launcher: ^6.1.11
  scrollable_positioned_list: ^0.3.8

* What platform did you found the issue
* What devices did you found the issue
* How are you initializing the plugin
* How are you creating the notification
* The output of `flutter doctor` command

OBS: To post a source code in your issue, please use the markdown below:

```Dart
print('Your source code goes here');
```

## **3 - How To Reproduce the Error**
The error is showing even before running the application

...or if you prefer, you can provide us a simple example app on GitHub with the issue already reproduced instead of the steps 2 and 3.

## **4 - Expected behavior**
This method worked before but its been a month since I last looked at the project.

## **5 - Screenshots**
![Screenshot from 2023-07-12 09-02-57](https://github.com/rafaelsetragni/awesome_notifications/assets/86406883/4791f585-6756-4c5d-a45b-72e3bdcf02ca)

## **6 - Additional context**
![Screenshot from 2023-07-12 09-02-57](https://github.com/rafaelsetragni/awesome_notifications/assets/86406883/bc7b58a9-f195-4096-9469-c23476069a67)

**Comment by JonHawke** [comment] 2023-07-19 16:31
I'm also encountering this issue too

**Comment by felipeparente** [comment] 2023-07-20 03:18
i'm too.
How i can get the click into notifications? Or in buttons?

**Comment by chris-herring** [comment] 2023-08-04 04:07
Hit the same issue. It was resolving awesome_notifications as version 0.6.something because there was a conflict with flutter_localizations on the intl library. Had to use dependency overrides to get 0.7.4 installed and setListeners now works.
I am a little concerned that there's been no updates for 9 months. I'm trying to decide whether to go this or flutter_local_notifications.

**Comment by moazelsawaf** [comment] 2023-08-05 15:22
As @chris-herring said, the problem is a confliction version with `intl` package.

You can solve the issue by just adding a **Dependency Override** for the `intl` package in `pubspec.yaml` as the following:

```YAML
dependencies:
  ...
  awesome_notifications: ^0.7.4+1
  ...

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ...

dependency_overrides:
  intl: ^0.18.1
```

**Closed** 2023-09-26 18:32 UTC
Labels: help wanted, good first issue
