### ISSUE TITLE
[Android] I cannot received Scheduled Notification when app is terminated

### ISSUE THREAD

**Issue by hammadpervez** [rafaelsetragni/awesome_notifications#408] opened 2022-01-31 20:56 UTC
When my app is in background or in foregorund I can receive notifications but once app is terminated. I cannot receive scheduled notification. I have tested app on different versions 8.0/7/9

```
 await AwesomeNotifications().initialize(
      null,
      [
        NotificationChannel(
          channelGroupKey: 'test_notification_channel',
          channelKey: 'test_channel',
          channelName: 'Test Notifications',
          channelDescription: 'Test for Notifications',
          defaultColor: Constants.primaryColor,
          ledColor: Constants.primaryTextColor,
        ),
      ],
      channelGroups: [
        NotificationChannelGroup(
          channelGroupkey: 'test_notification_channel',
          channelGroupName: 'Test Notifications',
        ),
      ],
      debug: true,
    );
```
```

  final localTime = await AwesomeNotifications().getLocalTimeZoneIdentifier();
    AwesomeNotifications().createNotification(
        schedule: NotificationInterval(
            timeZone: localTime, interval: interval, repeats: true),
        content: NotificationContent(
          id: 10,
          channelKey: 'test_channel',
          title: 'You will get notification as per duration set',

        ),actionButtons: [NotificationActionButton(key:stopNotificationKey, label: 'Stop Notification')]);
```
Here is AndroidMenifest.xml

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.app">
   <application
        android:label="App Title"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

**Comment by krispykalsi** [comment] 2022-02-05 05:07
Facing the same problem.

**Comment by krispykalsi** [comment] 2022-02-05 05:11
Duplicate of https://github.com/rafaelsetragni/awesome_notifications/issues/349

**Closed** 2022-09-29 18:33 UTC
