### ISSUE TITLE
IOS: Failed to build after Update Flutter to  2.0.2

### ISSUE THREAD

**Issue by bysano** [rafaelsetragni/awesome_notifications#135] opened 2021-03-16 16:09 UTC
@rafaelsetragni  Hi, mate ! I've updated my flutter to 2.0.2 and get this errors, there is solution in readme - i tried it many times , but result the same 

`ld: warning: Could not find or use auto-linked framework 'Flutter'
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FlutterStandardTypedData", referenced from:
      objc-class-ref in awesome_notifications(SwiftAwesomeNotificationsPlugin.o)
  "_OBJC_CLASS_$_FlutterError", referenced from:
      objc-class-ref in awesome_notifications(SwiftAwesomeNotificationsPlugin.o)
  "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
      objc-class-ref in awesome_notifications(SwiftAwesomeNotificationsPlugin.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-BY)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
[✓] Connected device (3 available)

**Comment by rafaelsetragni** [comment] 2021-03-16 16:14
This issue is a duplicate of [this topic](https://github.com/rafaelsetragni/awesome_notifications/issues/115)

**Closed** 2021-03-16 16:15 UTC
