### ISSUE TITLE
media button action crash

### ISSUE THREAD

**Issue by Ali1Ammar** [rafaelsetragni/awesome_notifications#81] opened 2021-01-05 11:36 UTC
i didn't use media button at all but 
app crashed on Galaxy Tab E 9.6 android 4.4.4 ( same from emulator  4.4)
with this error 
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sjaj.iq/com.sjaj.iq.MainActivity}: java.lang.IllegalArgumentException: MediaButtonReceiver component may not be null.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2429)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
       at android.app.ActivityThread.access$800(ActivityThread.java:166)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5590)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

i search and the answer to that problem was adding this  to AndroidManifest.xml
```
<receiver android:name="androidx.media.session.MediaButtonReceiver" >
   <intent-filter>
        <action android:name="android.intent.action.MEDIA_BUTTON" />
   </intent-filter>
</receiver>
```

then it work fine but with Galaxy Tab E 9.6 android 4.4.4 
but now i get 

```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver androidx.media.session.MediaButtonReceiver: java.lang.IllegalStateException: Could not find any Service that handles android.intent.action.MEDIA_BUTTON or implements a media browser service.
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4120)
       at android.app.ActivityThread.access$1600(ActivityThread.java:272)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8019)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```
this from Galaxy A10s android 10  i don't know app crash on startup  or it is just when recivce notifiction  i get it from crashlytics
but first error on 4.4.4 i get it from crashlytics and real user and i tested on emulator it is crash on startup

PS::
- i didn't use Media Button at all  but this error  appers on some devices 
-  
- I useed normal button

**Comment by Ali1Ammar** [comment] 2021-01-05 11:52
i will try this i don't know if it will work 
```java
public class NonNeeded extends BroadcastReceiver {

    @Override
    public void onReceive(Context context, Intent intent) {

    }
}
```
```xml
<receiver android:name=".NonNeeded" >
   <intent-filter>
        <action android:name="android.intent.action.MEDIA_BUTTON" />
   </intent-filter>
</receiver>
```

this will solve first problem 
but i don't know what will happens to second problem

**Comment by rafaelsetragni** [comment] 2021-01-05 12:47
What pluggin version are you using?

**Comment by Ali1Ammar** [comment] 2021-01-05 23:08
last version 0.0.5+4

**Comment by Ali1Ammar** [comment] 2021-01-13 13:29
i discover that all error like this
`Fatal Exception: java.lang.RuntimeException: Unable to start receiver androidx.media.session.MediaButtonReceiver: java.lang.IllegalStateException: Could not find any Service that handles android.intent.action.MEDIA_BUTTON or implements a media browser service.`

always happens when device status is 100% background
it happens to
Galaxy A50 , Galaxy M11 ,  Galaxy A30 , Galaxy A11 
Galaxy A10s
Galaxy A51
Galaxy A21s
all android 10 

and also amazon KFDOWI android 5  rooted 100%

**Comment by rafaelsetragni** [comment] 2021-01-15 11:24
I guess I discovered what happened. Seems like Android 10 require that this media button need to be declared inside AndroidManifest and inherited by some other class inside the project. But all my Android 10 simulators are crashing. Can you test it for me? Ill send to you a git branch with the files to test.

**Comment by rafaelsetragni** [comment] 2021-03-07 15:39
New version released. Check to see if the problem is resolved.

**Comment by rafaelsetragni** [comment] 2021-11-01 06:17
I gonna close this issue for now, since there is no more activity in 6 months. But you can reopen it, in case you judge necessary.

**Comment by proczak1** [comment] 2021-11-02 09:06
Same case as @Ali1Ammar  - not using any media buttons but this happens:
Fatal Exception: java.lang.RuntimeException: Unable to start receiver androidx.media.session.MediaButtonReceiver: java.lang.IllegalStateException: Could not find any Service that handles android.intent.action.MEDIA_BUTTON or implements a media browser service...

Tons of users experiencing that issue :(

**Comment by rafaelsetragni** [comment] 2021-11-02 09:18
Try to go at Manifest.xml and erase the lines above:

File location:

![image](https://user-images.githubusercontent.com/40064496/139819270-cee38112-4d6b-4471-9b05-9c1f0f1d35f9.png)

Lines to erase:

```xml
        <receiver
            android:name="androidx.media.session.MediaButtonReceiver"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MEDIA_BUTTON" />
            </intent-filter>
        </receiver>
```

**Comment by proczak1** [comment] 2021-11-02 09:27
Thank you for quick response. I will test it and say if it worked

**Comment by rafaelsetragni** [comment] 2021-11-02 09:50
If you found any dificult, you can join in our Discord chat group:
https://discord.com/invite/MP3sEXPTnx

**Comment by rafaelsetragni** [comment] 2021-11-02 17:01
Version 0.6.16 released! Check if this solved your issue.

**Comment by rafaelsetragni** [comment] 2021-11-02 21:57
Version 0.6.16 released! Check if this solved your issue.

**Closed** 2021-11-03 13:54 UTC
Labels: bug
