### ISSUE TITLE
Notification fires itself over and over again on crontabExpression

### ISSUE THREAD

**Issue by fadone** [rafaelsetragni/awesome_notifications#850] opened 2023-09-05 21:09 UTC
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

Notification is firing itself again and again when using crontabExpression.

## **2 - Provide us as much information as possible**

To help us to understand your issue, provide with your bug report all the relevant informations, such as:

Plugins
```
  animated_bottom_navigation_bar: ^1.2.0
  app_bar_with_search_switch: ^1.5.4
  awesome_notifications: ^0.7.4+1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.3.10
  http: ^1.1.0
  image_picker: ^1.0.4
  json_annotation: ^4.8.1
  page_transition: ^2.0.9
  timezone: ^0.9.2
```

Platform
```Android```

Devices
```Pixel 6 Pro API 33 (android-x64 emulator)```

Initilization
```Dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  AwesomeNotifications().initialize(
    'resource://drawable/plant_icon',
    [
      NotificationChannel(
          channelGroupKey: 'basic_channel_group',
          channelKey: 'basic_channel',
          channelName: 'Basic notifications',
          channelDescription: 'Notification channel for basic tests',
          defaultColor: const Color(0xFF9D50DD),
          ledColor: Colors.white)
    ],
    channelGroups: [
      NotificationChannelGroup(
          channelGroupKey: 'basic_channel_group',
          channelGroupName: 'Basic group')
    ],
    debug: true,
  );

  AwesomeNotifications().isNotificationAllowed().then((isAllowed) {
    if (!isAllowed) {
      AwesomeNotifications().requestPermissionToSendNotifications();
    }
  });

  runApp(const ProviderScope(child: MainApp()));
}
```

Creating notifications
```Dart
await AwesomeNotifications().createNotification(
  content: NotificationContent(
    id: 100,
    channelKey: 'basic_channel',
    title: 'Notification title',
    body:
        'Notification body',
    actionType: ActionType.Default,
  ),
  schedule: NotificationAndroidCrontab(
    initialDateTime: selectedPreviousDate,
    crontabExpression: '0 0 2 */1 * ? *',
    timeZone: await AwesomeNotifications()
        .getLocalTimeZoneIdentifier(),
    repeats: true,
    allowWhileIdle: true,
  ),
);

```

Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.22621.2134], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.1)
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

## **3 - How To Reproduce the Error**

1. Given code above

## **4 - Expected behavior**
Notification firing itself over and over again until the notification is cancelled by user.

## **6 - Additional context**
Logs

Creating notification
```
D/Android: [Awesome Notifications](10493): New notification creation event (AwesomeEventsReceiver:209)
D/Android: [Awesome Notifications](10493): Scheduled created (NotificationScheduler:225)
D/Android: [Awesome Notifications](10493): Notification scheduled in 50ms (NotificationScheduler:235)
```
Notification fired  and then cancelled
```
D/Android: [Awesome Notifications](10493): New notification display event (AwesomeEventsReceiver:229)
D/Android: [Awesome Notifications](10493): Notification displayed in 49ms (NotificationSender:198)
D/Android: [Awesome Notifications](10493): Notification rescheduled in 28ms (NotificationScheduler:235)
D/Android: [Awesome Notifications](10493): New notification display event (AwesomeEventsReceiver:229)
D/Android: [Awesome Notifications](10493): Notification displayed in 14ms (NotificationSender:198)
D/Android: [Awesome Notifications](10493): Notification rescheduled in 16ms (NotificationScheduler:235)
D/Android: [Awesome Notifications](10493): New notification display event (AwesomeEventsReceiver:229)
D/Android: [Awesome Notifications](10493): Notification displayed in 26ms (NotificationSender:198)
D/Android: [Awesome Notifications](10493): Notification rescheduled in 38ms (NotificationScheduler:235)
D/Android: [Awesome Notifications](10493): New notification display event (AwesomeEventsReceiver:229)
D/Android: [Awesome Notifications](10493): Notification displayed in 35ms (NotificationSender:198)
D/Android: [Awesome Notifications](10493): Notification rescheduled in 30ms (NotificationScheduler:235)
D/Android: [Awesome Notifications](10493): Schedule 100 cancelled (AwesomeNotificationsPlugin:718)
```

**Comment by rafaelsetragni** [comment] 2023-09-29 23:57
This bug was fixed in the last update. You just need to add the pubspec.yaml below:

```yaml
  # Awesome plugins
  awesome_notifications_core: ^0.7.6 # use the latest available
  awesome_notifications: any # <- this version will be managed by core plugin
  awesome_notifications_fcm: any # <- this version will be managed by core plugin
```

**Comment by unoHdmedi** [comment] 2023-10-31 05:35
I also faced the same situation, changed it, but I have the same problem. It only occurs in android and not in ios.
`  awesome_notifications_core: ^0.8.0 # <~ always ensure to use the latest version
  awesome_notifications: any # <~ this version is managed by awesome_notifications_core package
  awesome_notifications_fcm: any`

**Comment by guyluz11** [comment] 2023-12-06 10:31
@unoHdmedi  When using repeast you should also set `second` and `millisecond`.
When they are not set the notification will keep repeating, please try it and add it to your example.

**Comment by rafaelsetragni** [comment] 2023-12-16 18:59
Exactly, you need to set second and millisecond to 0, otherwise all seconds in the minute selected are valid and will fire a new notification.

**Closed by rafaelsetragni** 2023-12-16 18:59 UTC
Labels: bug, in discussion

**Comment by brunoferdias** [comment] 2024-02-10 15:44
note that the problem of incorrect triggering is resolved when you don't put the start date, the problem is that I need to use the date
