### ISSUE TITLE
Intl Package Version issue

### ISSUE THREAD

**Issue by chantikakitapalli** [rafaelsetragni/awesome_notifications#815] opened 2023-07-12 06:02 UTC
Getting issues while using other plugins with this, because they updated the "intl" version to "0.18.1". In this plugin still, 0.17.0 is there. Please update the "intl" version.

**Comment by gnunicorn** [comment] 2023-08-03 18:42
you gotta use the 0.7.5-dev.3 pre-release version for now.

**Comment by Leffe108** [comment] 2023-08-13 22:06
For others who have other dependencies that need intl 18.0, you can use this to resolve the 18.0 vs 18.1 conflict. Note though that you will want to remove the override once all libraries has settled on 18.1.

```yaml
dependencies:
  awesome_notifications: ^0.7.5-dev.1
dependency_overrides:
  intl: ^0.18.0
```

**Comment by Leffe108** [comment] 2023-08-13 22:09
It looks like this issue is a duplicate of https://github.com/rafaelsetragni/awesome_notifications/issues/735

**Closed** 2023-09-26 18:32 UTC
Labels: help wanted, good first issue
