### ISSUE TITLE
Action Buttons don't appears on IOS 14

### ISSUE THREAD

**Issue by bysano** [rafaelsetragni/awesome_notifications#27] opened 2020-11-02 19:58 UTC
`  AwesomeNotifications().createNotification(
      content: NotificationContent(
        id: 11,
        channelKey: 'big_picture',
        title: 'asdasd!!!',
        bigPicture: 'https://media.wired.com/photos/598e35994ab8482c0d6946e0/master/w_2560%2Cc_limit/phonepicutres-TA.jpg',
        body: 'Hi there!',
          notificationLayout: NotificationLayout.BigPicture
      ),
      actionButtons: [
        NotificationActionButton(
          key: 'REPLY',
          label: 'Reply',
          autoCancel: true,
          buttonType: ActionButtonType.InputField,
        ),
        NotificationActionButton(
            key: 'READ', label: 'Mark as read', autoCancel: true),
        NotificationActionButton(
            key: 'ARCHIVE', label: 'Archive', autoCancel: true)
      ]);`

![Simulator Screen Shot - iPhone 11 Pro - 2020-11-02 at 22 59 13](https://user-images.githubusercontent.com/24550731/97913386-41ebc080-1d5f-11eb-8aca-f3098e17006e.png)

**Comment by rafaelsetragni** [comment] 2020-11-03 13:04
What plugin version are you using?

**Comment by bysano** [comment] 2020-11-03 13:30
@rafaelsetragni  0.0.4+2

**Comment by rafaelsetragni** [comment] 2020-11-03 14:01
I couldn't reproduce your error. I pasted your example entirely and it worked as expected.

![image](https://user-images.githubusercontent.com/40064496/97994117-b9533b80-1dc3-11eb-9041-12f53f1dbcf4.png)

Maybe its a misconfiguration of your app. Certifies to follow all the steps in the README file.

Im using iOS 14.1 and XCode 12.1

If it do not work, you can send me a simple example on GitHub.

**Comment by bysano** [comment] 2020-11-03 16:03
Maybe i have some problem with notification Service extension . do we need to add for that  new App Groups on the Signing & Capabilities tab ?

**Comment by rafaelsetragni** [comment] 2020-11-03 18:14
This function should work without extensions.

**Service extension** is used in cases of remote push notification. **Content extension** bring more styles than default iOS.

Right now is not necessary to add App Groups, but in the next releases that config will be needed.

I saw in your first example that your app name wasnt correctly loaded. Maybe this is a tip of whats goin on with your app.

**Comment by bysano** [comment] 2020-11-04 10:21
Thanks a lot for answers! 
https://github.com/bysano/flutter-test

**Comment by rafaelsetragni** [comment] 2020-11-04 14:25
You are correct, its a bug! Thank you so much!

This is a bug in the past while i only did registered the "Notification Category" on the initizalization. This bug was fixed in my local files because i already improve the category identifier for the next releases. Thats why i couldnt reproduce your error on my machine.

Thankfuly to your example i was capable to discovery this old issue. Thank you again.
I only finishing the display and create event in push notifications and i will publish a new version with this problem fix.

This should happen today or even tomorrow.
I will warning you as soon this version goes to live.

**Comment by rafaelsetragni** [comment] 2020-11-10 21:47
Version 0.0.5 finally released!

But you gonna need to protect your native resources against minification inserting the prefix "res_" in your image or sound file names. You can see more about it [here in the README file](https://github.com/rafaelsetragni/awesome_notifications#media-source-types).

Also i simplified the iOS installation. Please, update it and tell me if is more easy than before.

Call me here if you continue with issues on this new version.

**Comment by rafaelsetragni** [comment] 2020-11-12 17:10
I gonna close this topic just to help me to organize the issues.
If you want to continue with this request, just reopen it.

**Closed** 2020-11-12 17:10 UTC
Labels: bug
