### ISSUE TITLE
Fire action without open the app

### ISSUE THREAD

**Issue by saharvx9** [rafaelsetragni/awesome_notifications#241] opened 2021-07-29 06:56 UTC
i did some research on this library,maybe i mistaken,
there is away to click on button without open the app and fire the action only?

**Comment by jja08111** [comment] 2021-07-29 12:03
This is the next feature. Duplicate of #56.

**Comment by clebemachado** [comment] 2021-07-29 13:50
I'm using it like this and it worked at first
Just use the buttonType: ActionButtonType.KeepOnTop,

`
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  var msg = message.notification;
  var key = message.data['local'];

  await AwesomeNotifications().createNotification(
    content: NotificationContent(
      id: 0,
      channelKey: 'basic_channel',
      title: msg.title,
      body: msg.body,
      color: Colors.blue,
    ),
    actionButtons: [
      NotificationActionButton(
        key: key != "" ? key : null,
        label: 'Visto',
        buttonType: ActionButtonType.KeepOnTop,
      ),
    ],
  );
}
`

and

`
@override
  void initState() {
    super.initState();
    AwesomeNotifications().actionStream.listen((event) async {
      if (event.buttonKeyPressed != null) {
        String key = event.buttonKeyPressed.toString();
        await status(key);
      }
    });
  }
`

In this case I'm using FMC with python, but I found a little problem, when the background action doesn't work after a long time.

**Comment by clebemachado** [comment] 2021-07-29 13:56
I got it using ActionButtonType.KeepOnTop,
Note: I'm using FCM - Python to notify

![image](https://user-images.githubusercontent.com/66011013/127504335-f67d0498-dd18-44a0-9749-2ff6de31429d.png)

In initSate I added a listen, and tested it for hours and it worked, but I think at some point it will stop listening

![image](https://user-images.githubusercontent.com/66011013/127504631-d88e4074-0e36-4997-9e8a-5959cbafb2ae.png)

Obs2: I started now on flutter, if you're talking nonsense, sorry

**Comment by rafaelsetragni** [comment] 2022-09-29 18:03
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!

**Closed by rafaelsetragni** 2022-09-29 18:03 UTC
