### ISSUE TITLE
Notification Type call is not working on release mode

### ISSUE THREAD

**Issue by krupikivan** [rafaelsetragni/awesome_notifications#585] opened 2022-10-09 02:32 UTC
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

OBS: avoid to use the expression **"its not working"** or **"is working"** or any other variation. These expressions can mean anything and at same time doesn´t bring any useful information. As soon you rewrite these expressions, you naturally going to be more precise and clear.

## **2 - Provide us as much information as possible**

To help us to understand your issue, provide with your bug report all the relevant informations, such as:

* Your plugins list inside the file `pubspec.yaml` (at least all notification plugins)
* What platform did you found the issue: Android
* What devices did you found the issue: One Plus 8
* How are you initializing the plugin: Through Get_it package, regular notification works
* How are you creating the notification: TYPE CALL
* The output of `flutter doctor` command

OBS: To post a source code in your issue, please use the markdown below:

```Dart
print('Your source code goes here');
```

## **3 - How To Reproduce the Error**

1. Trying to display NotificationCategory.Call on RELEASE MODE

...or if you prefer, you can provide us a simple example app on GitHub with the issue already reproduced instead of the steps 2 and 3.

## **6 - Additional context**
This is the issue
[Awesome Notifications]: class g.e.b.f.k isn't parameterized (SharedManager:4)

**Comment by krupikivan** [comment] 2022-10-09 02:36
10-08 22:33:14.952 28444 28479 V ActivityThread: scheduleReceiver info = ActivityInfo{b22ab38 com.google.firebase.iid.FirebaseInstanceIdReceiver} intent = Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x11080010 pkg=com.examplenotifapp cmp=com.examplenotifapp/com.google.firebase.iid.FirebaseInstanceIdReceiver (has extras) } sync = true hasCode = 97268623
10-08 22:33:14.961  9637 11446 W OplusExSystemServiceHelper: checkOplusExSystemService intent getComponent is null
10-08 22:33:14.982 28444 28479 V ActivityThread: scheduleReceiver info = ActivityInfo{b4d234d io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingReceiver} intent = Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x11080010 pkg=com.examplenotifapp cmp=com.examplenotifapp/io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingReceiver (has extras) } sync = true hasCode = 264378376
10-08 22:33:14.982 28444 28444 D FLTFireMsgReceiver: broadcast received for message
10-08 22:33:14.994 28444 28444 E Android: [Awesome Notifications]: class g.e.b.f.k isn't parameterized (SharedManager:4)
10-08 22:33:14.994 28444 28444 W System.err: me.carda.awesome_notifications.r.j.a: class g.e.b.f.k isn't parameterized
10-08 22:33:14.994 28444 28444 W System.err: 	at g.e.b.a.p.g(Unknown Source:15)
10-08 22:33:14.994 28444 28444 W System.err: 	at g.e.b.f.c.a(Unknown Source:12)
10-08 22:33:14.994 28444 28444 W System.err: 	at g.e.b.f.k.<init>(Unknown Source:3)
10-08 22:33:14.994 28444 28444 W System.err: 	at me.carda.awesome_notifications.r.p.h.<init>(Unknown Source:0)
10-08 22:33:14.994 28444 28444 W System.err: 	at me.carda.awesome_notifications.r.p.i.c(Unknown Source:7)
10-08 22:33:14.994 28444 28444 W System.err: 	at me.carda.awesome_notifications.r.n.a.o(Unknown Source:9)
10-08 22:33:14.994 28444 28444 W System.err: 	at me.carda.awesome_notifications.r.n.f.a(:1)
10-08 22:33:14.995 28444 28444 W System.err: 	at me.carda.awesome_notifications.core.managers.t.c(Unknown Source:33)
10-08 22:33:14.995 28444 28444 W System.err: 	at me.carda.awesome_notifications.core.managers.e.e(Unknown Source:53)
10-08 22:33:14.995 28444 28444 W System.err: 	at me.carda.awesome_notifications.r.f.a.d(Unknown Source:14)
10-08 22:33:14.995 28444 28444 W System.err: 	at me.carda.awesome_notifications.r.o.c.a(:2)
10-08 22:33:14.995 28444 28444 W System.err: 	at me.carda.awesome_notifications.r.o.g.c(:3)
10-08 22:33:14.995 28444 28444 W System.err: 	at me.carda.awesome_notifications.r.o.c.f(Unknown Source:17)
10-08 22:33:14.995 28444 28444 W System.err: 	at me.carda.awesome_notifications.r.a.r(:2)
10-08 22:33:14.995 28444 28444 W System.err: 	at me.carda.awesome_notifications.k.l(:2)
10-08 22:33:14.995 28444 28444 W System.err: 	at me.carda.awesome_notifications.k.onMethodCall(:26)
10-08 22:33:14.995 28444 28444 W System.err: 	at j.a.f.a.A.a(Unknown Source:17)
10-08 22:33:14.995 28444 28444 W System.err: 	at io.flutter.embedding.engine.o.s.j(Unknown Source:11)
10-08 22:33:14.995 28444 28444 W System.err: 	at io.flutter.embedding.engine.o.s.k(Unknown Source:20)
10-08 22:33:14.995 28444 28444 W System.err: 	at io.flutter.embedding.engine.o.a.run(Unknown Source:12)
10-08 22:33:14.995 28444 28444 W System.err: 	at android.os.Handler.handleCallback(Handler.java:938)
10-08 22:33:14.995 28444 28444 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-08 22:33:14.995 28444 28444 W System.err: 	at android.os.Looper.loopOnce(Looper.java:233)
10-08 22:33:14.995 28444 28444 W System.err: 	at android.os.Looper.loop(Looper.java:344)
10-08 22:33:14.995 28444 28444 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8212)
10-08 22:33:14.995 28444 28444 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
10-08 22:33:14.995 28444 28444 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
10-08 22:33:14.995 28444 28444 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
10-08 22:33:14.997 11115 17816 W OplusExSystemServiceHelper: checkOplusExSystemService intent getComponent is null
10-08 22:33:14.998 11115 11115 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }
10-08 22:33:14.998 11115 11115 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }
10-08 22:33:15.045  9637  4232 W NetworkScheduler: Error inserting flex_time=868000 job_id=-1 period=1737000 source=16 requires_charging=0 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService user_id=0 target_package=com.google.android.gms tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG task_type=0 required_idleness_state=0 service_kind=0 source_version=223616000 persistence_level=1 preferred_charging_state=1 required_network_type=0 runtime=1665282795042 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0 [CONTEXT service_id=218 ]
10-08 22:33:15.045  9637  4232 W NetworkScheduler: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE)
10-08 22:33:15.045  9637  4232 W NetworkScheduler: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
10-08 22:33:15.045  9637  4232 W NetworkScheduler: 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:946)
10-08 22:33:15.045  9637  4232 W NetworkScheduler: 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
10-08 22:33:15.045  9637  4232 W NetworkScheduler: 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:89)
10-08 22:33:15.045  9637  4232 W NetworkScheduler: 	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1702)
10-08 22:33:15.045  9637  4232 W NetworkScheduler: 	at android.database.sqlite.SQLiteDatabase.insertOrThrow(SQLiteDatabase.java:1597)
10-08 22:33:15.045  9637  4232 W NetworkScheduler: 	at bpxz.g(:com.google.android.gms@223616045@22.36.16 (190408-476895098):52)
10-08 22:33:15.045  9637  4232 W NetworkScheduler: 	at bpws.n(:com.google.android.gms@223616045@22.36.16 (190408-476895098):3)
10-08 22:33:15.045  9637  4232 W NetworkScheduler: 	at bpws.u(:com.google.android.gms@223616045@22.36.16 (190408-476895098):20)
10-08 22:33:15.045  9637  4232 W NetworkScheduler: 	at bpws.h(:com.google.android.gms@223616045@22.36.16 (190408-476895098):3)
10-08 22:33:15.045  9637  4232 W NetworkScheduler: 	at bpsj.run(:com.google.android.gms@223616045@22.36.16 (190408-476895098):9)
10-08 22:33:15.045  9637  4232 W NetworkScheduler: 	at zjg.c(:com.google.android.gms@223616045@22.36.16 (190408-476895098):6)
10-08 22:33:15.045  9637  4232 W NetworkScheduler: 	at zjg.run(:com.google.android.gms@223616045@22.36.16 (190408-476895098):7)
10-08 22:33:15.045  9637  4232 W NetworkScheduler: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-08 22:33:15.045  9637  4232 W NetworkScheduler: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-08 22:33:15.045  9637  4232 W NetworkScheduler: 	at zom.run(:com.google.android.gms@223616045@22.36.16 (190408-476895098):0)
10-08 22:33:15.045  9637  4232 W NetworkScheduler: 	at java.lang.Thread.run(Thread.java:920)
10-08 22:33:15.047  9637  4232 W NetworkScheduler: Error inserting flex_time=867000 job_id=-1 period=1736000 source=16 requires_charging=0 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService user_id=0 target_package=com.google.android.gms tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG task_type=0 required_idleness_state=0 service_kind=0 source_version=223616000 persistence_level=1 preferred_charging_state=1 required_network_type=0 runtime=1665282795042 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0 [CONTEXT service_id=218 ]

**Comment by rafaelsetragni** [comment] 2022-10-09 11:02
Sorry but I can't help you with the information you paste me. I am not able to reproduce your error in any compilation mode. In all conditions i was able to create a call notification, receive it and redirect the user to calling page, even if the user accept the call using the notification button.

But that's not all, I'm going to need to close this topic, **since you didn't follow the rules for posting this topic**. I really need the form to be correctly filled in and the rules contained in it to be followed, otherwise I can't even understand how you built your application. And that changes everything.

If possible, try to build a small example application with the error and share it with me here on GitHub. This is the best solution and that way I can perfectly see how you implemented everything and solve the problem.

**Closed by rafaelsetragni** 2022-10-09 11:02 UTC
Labels: bug, in triage
