### ISSUE TITLE
iOS build failed with missing code errors

### ISSUE THREAD

**Issue by rutaba1** [rafaelsetragni/awesome_notifications#84] opened 2021-01-07 13:46 UTC
HI. I'm facing a strange issue here. I'm able to run iOS project with no problem at all but when I push it to git my colleague takes clone of the same project this error occurs: 

/Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.0.5+4/ios/Classes/lib/notifications/models/NotificationContentModel.swift:164:48: error: missing argument label 'mediaPath:' in call
                    BitmapUtils.getMediaSourceType(icon) != MediaSource.Resource
                                                   ^
                                                   mediaPath: 
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.0.5+4/ios/Classes/lib/notifications/models/NotificationContentModel.swift:167:42: error: value of optional type 'String?' must be unwrapped to a value of type 'String'
                        msg: "Small icon ('"+icon+"') must be a valid media native resource type.")
                                             ^
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.0.5+4/ios/Classes/lib/notifications/models/NotificationContentModel.swift:167:42: note: coalesce using '??' to provide a default when the optional value contains 'nil'
                        msg: "Small icon ('"+icon+"') must be a valid media native resource type.")
                                             ^
                                                  ?? <#default value#>
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.0.5+4/ios/Classes/lib/notifications/models/NotificationContentModel.swift:167:42: note: force-unwrap using '!' to abort execution if the optional value contains 'nil'
                        msg: "Small icon ('"+icon+"') must be a valid media native resource type.")
                                             ^
                                                 !
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.0.5+4/ios/Classes/lib/SwiftAwesomeNotificationsPlugin.swift:87:84: warning: 'UILocalNotification' was deprecated in iOS 10.0: Use UserNotifications Framework's UNNotificationRequest
        public func application(_ application: UIApplication, didReceive notification: UILocalNotification) {
                                                                                       ^
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.0.5+4/ios/Classes/lib/SwiftAwesomeNotificationsPlugin.swift:106:17: warning: instance method 'messaging(_:didReceiveRegistrationToken:)' nearly matches optional requirement 'messaging(_:didReceiveRegistrationToken:)' of protocol 'MessagingDelegate'
        public func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String) {
                    ^
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.0.5+4/ios/Classes/lib/SwiftAwesomeNotificationsPlugin.swift:106:17: note: add '@objc' to provide an Objective-C entrypoint
        public func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String) {
                    ^
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.0.5+4/ios/Classes/lib/SwiftAwesomeNotificationsPlugin.swift:106:17: note: move 'messaging(_:didReceiveRegistrationToken:)' to an extension to silence this warning
        public func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String) {
                    ^
    FirebaseMessaging.MessagingDelegate:2:19: note: requirement 'messaging(_:didReceiveRegistrationToken:)' declared here
        optional func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String)
                      ^
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.0.5+4/ios/Classes/lib/SwiftAwesomeNotificationsPlugin.swift:43:24: warning: immutable value 'scheduleJsonData' was never used; consider replacing with '_' or removing it
                    if let scheduleJsonData:String = userInfo[Definitions.PUSH_NOTIFICATION_SCHEDULE] as? String {
                           ^~~~~~~~~~~~~~~~
                           _
                           
                           
                           
I'm not sure what this error even means and how to handle this.

**Comment by ahmetakil** [comment] 2021-01-07 14:07
Replace '"+icon+"' with '"+icon!+"' 

or if you try to run the code in Xcode and see the errors you can simply click fix

**Comment by rutaba1** [comment] 2021-01-07 17:30
@ahmetakil I have noticed something strange in this error as well. I have version 0.0.5+3 of this plugin my pub spec.yaml file and in error it shows plugin awesome_notifications-0.0.5+4

**Comment by rafaelsetragni** [comment] 2021-01-09 16:20
Native media resources need to be included inside project using XCode. Maybe this was only done in your local machine.

**Comment by rutaba1** [comment] 2021-01-10 09:23
@rafaelsetragni so do I need to import notification icon separately in Assets.xcassets directory in Xcode? I'm not sure if I had done this in my local machine either.

**Comment by Mohanedy98** [comment] 2021-01-19 19:49
I have the same issue too with the same output

**Comment by abdoutech93** [comment] 2021-01-20 16:56
I getting the same error.

**Comment by rafaelsetragni** [comment] 2021-01-26 18:47
Great job! A simple change, but it makes the plugin more robust. Thank you very much!

**Comment by tashone** [comment] 2021-01-31 20:52
I'm sorry for stupid question. But how can I force cocoapod to update sources with those changes? I still have this error:(

**Comment by rafaelsetragni** [comment] 2021-03-05 22:55
That happens because your ios folder was created on a older flutter version and now it will not work on new one. You unfortunally Try to update the Cocoa pods as bellow:

* Update your Cocoa pod instalation with `sudo gem install cocoapods`
* Update your Flutter directory with `flutter upgrade`
* Run `pod update` and `pod install` inside your iOS flutter directory

**Comment by rafaelsetragni** [comment] 2021-03-07 15:39
New version released. Check to see if the problem is resolved.

**Comment by rafaelsetragni** [comment] 2021-11-01 06:17
I gonna close this issue for now, since there is no more activity in 6 months. But you can reopen it, in case you judge necessary.

**Closed by rafaelsetragni** 2021-11-01 06:17 UTC
Labels: bug, help wanted
