### ISSUE TITLE
Cannot build on iOS

### ISSUE THREAD

**Issue by derBeukatt** [rafaelsetragni/awesome_notifications#39] opened 2020-11-17 14:58 UTC
As the title states, i cannot build my app using your library on iOS.
Ich do not use the lib on iOS at all, i just need it for android and cannot exclude it from iOS build.

Environment:

- MacOS 10.15.7
- Flutter 1.22.4
- XCode 12.1
- lib version 0.0.5+2

It throws the following error:

awesome_notifications-0.0.5+2/ios/Classes/lib/SwiftAwesomeNotificationsPlugin.swift:104:17: error: parameter of 'messaging(_:didReceiveRegistrationToken:)' has different optionality than required by protocol 'MessagingDelegate'
        public func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String) {
                    ^
                                                                                                  ?
    FirebaseMessaging.MessagingDelegate:2:19: note: requirement 'messaging(_:didReceiveRegistrationToken:)' declared here
        optional func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?)

Suggesting the parameter must be optional. I made it optional and unwrapped inside your swift plugin and the build succeeded. Maybe you can give more insight.

**Comment by derBeukatt** [comment] 2020-11-23 07:43
Hey there.

Is this just a specific problem for me or does anyone else run into this.

**Comment by rafaelsetragni** [comment] 2020-11-23 20:56
I was unable to reproduce your error. What steps did you take to create your iOS app?

Try modifying the messaging method below in your local code:

https://github.com/rafaelsetragni/awesome_notifications/blob/b3e4da96f0302fef43f4c801d819dad044021332/ios/Classes/lib/SwiftAwesomeNotificationsPlugin.swift#L97

**Comment by derBeukatt** [comment] 2020-11-24 06:44
Hi. Thanks for your answer.

I was just normally building my app via "flutter build ios" and the error occured.
I already did modify the following code:

[https://github.com/rafaelsetragni/awesome_notifications/blob/b3e4da96f0302fef43f4c801d819dad044021332/ios/Classes/lib/SwiftAwesomeNotificationsPlugin.swift#L104](url)

```
public func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String) {
        print("Firebase registration token: \(fcmToken)")

        let dataDict:[String: String] = ["token": fcmToken]
        NotificationCenter.default.post(name: Notification.Name("FCMToken"), object: nil, userInfo: dataDict)
        // TODO: If necessary send token to application server.
        // Note: This callback is fired at each app startup and whenever a new token is generated.
}
```
to the following
```
public func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
        if let unwrapped = fcmToken {
            print("Firebase registration token: \(unwrapped)")
            let dataDict:[String: String] = ["token": unwrapped]
            NotificationCenter.default.post(name: Notification.Name("FCMToken"), object: nil, userInfo: dataDict)
            // TODO: If necessary send token to application server.
            // Note: This callback is fired at each app startup and whenever a new token is generated.
        }
}
```
But I just don't know why I had to do this.

**Comment by rafaelsetragni** [comment] 2020-11-24 13:19
You are rigth. My messaging method is deprecated, thats why you couldnt compile the final version in your app. I gonna update it.
Did you use another firebase services in your app? What version are they?

**Comment by derBeukatt** [comment] 2020-11-25 11:36
> You are rigth. My messaging method is deprecated, thats why you couldnt compile the final version in your app. I gonna update it.
> Did you use another firebase services in your app? What version are they?

I use FirebaseMessaging 7.1.0. That is the version installed by cocoapods.

>Better! Do you wanna do a fork and send me this fix? Your name will be included as this project contributor.

Does this mean you experience the same problem after updating to the above version?
If so, I gladly provide the fix. Just don't want to break it for somebody else.

**Comment by rafaelsetragni** [comment] 2020-11-25 14:26
Im did not experienced this issue. For me, when i applyied your changes, XCode complains about the override operation not being possible due the messaging methos be different.

But send me your fork. This way i can merge your source and see every change that you did in your source and figure out whats goin on.

**Comment by rafaelsetragni** [comment] 2020-11-25 15:30
In fact, im merged your changes into my local files, and the messaging firebase method that you sent always complain about the override operation not being possible. In this way, i could not reproduce your error.

But in think im figuring out whats going on. You said that youre using FirebaseMessaging 7.1.0, but you want to say firebase_messaging: ^7.1.0 instead?

This plugin is not necessary to send push notifications using awesome_notifications. All that you need is inside the plugin and you only need to follow the steps extrictely inside [Using Firebase Services (Optional) topic](https://github.com/rafaelsetragni/awesome_notifications#using-firebase-services-optional). Is not necessary to use any other plugin or implement any kotlin or java extra script.

Maybe firebase_messaging version is conflicting with my awesome_notifications firebase library, because firebase_messaging is using another library version, that overides mine.

**Comment by rafaelsetragni** [comment] 2020-11-25 17:11
Bingo! That was exactely what happened!

![image](https://user-images.githubusercontent.com/40064496/100259160-a8ab6680-2f26-11eb-98d6-dfcff67ffa77.png)
![image](https://user-images.githubusercontent.com/40064496/100259028-7f8ad600-2f26-11eb-829d-eca242bb7a90.png)

After update my libraries with `pod update`, i got your error!

On the newer Firebase version, the firebase team did a lot of changes, including change the method messaging without keep a deprecated version. So, all the sources bellow 7.1.0 will break. And they also changed a lot of things on Android sdk, as to deprecate the entire FirebaseInstance iil.

You got the newer firebase version after install a firebase plugin or update your pod files. Thats why you have those issues.

All the others awesome_notification developers gonna face the same after update the firebase package. So your change is totaly legit.

The problem that i facing is how to keep both methods working on same time to not injure the olders projects.

Can you cancel the current pull request to `master` branch and send the same pull request to `update-firebase-sdk` branch instead? Theres a lot changes to do on Android side as well.

**Comment by derBeukatt** [comment] 2020-11-26 06:38
Yeah that is exactly what I was hoping was not happening.
But now that we now the problem it is maybe fixable.
If you need anything else from me, don't hesitate to ask. Thanks for your effort :)

**Comment by rafaelsetragni** [comment] 2020-11-26 15:48
Ive merged your pull request and included a suport for older versions, as the code bellow. This way, both library versions are compatible with the core code being reusable:

```swift

    // For Firebase Messaging versions older than 7.0
    // https://github.com/rafaelsetragni/awesome_notifications/issues/39
    public func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String) {
        
        didReceiveRegistrationToken(messaging, fcmToken: fcmToken)
    }
    
    public func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
        
        if let unwrapped = fcmToken {
            didReceiveRegistrationToken(messaging, fcmToken: unwrapped)
        }
    }
    
    private func didReceiveRegistrationToken(_ messaging: Messaging, fcmToken: String){
        
        print("Firebase registration token: \(fcmToken)")
        let dataDict:[String: String] = ["token": fcmToken]
        NotificationCenter.default.post(name: Notification.Name("FCMToken"), object: nil, userInfo: dataDict)
    }
```

**Closed** 2021-11-01 06:03 UTC
Labels: enhancement
